name: ftp-deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Deploy ke Rumahweb via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy ke Rumahweb via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ruangbicara.online
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
