name: sftp-deploy

on:
  push:
    branches:
      - main

jobs:
  sftp-deploy:
    name: Deploy ke Rumahweb via SFTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy ke Rumahweb via SFTP
        uses: SamKirkland/SFTP-Deploy-Action@v1.0.0  # <-- Ganti ke action SFTP dari Sam Kirkland
        with:
          server: ruangbicara.online
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remote-path: public_html/  # <-- Gunakan remote-path yang relatif
