name: sftp-deploy

on:
  push:
    branches:
      - main

jobs:
  sftp-deploy:
    name: Deploy ke Rumahweb via SFTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy ke Rumahweb via SFTP
        uses: appleboy/sftp-action@master
        with:
          host: ruangbicara.online
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          target: /home/ruax7678/public_html/
