name: Auto Deploy via PHP Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call PHP Deploy Script
        run: |
          # URL sekarang mengarah ke dalam public_html
          curl "https://ruangbicara.online/scripts/deploy.php"
